default_language_version:
  python: python3.8

default_stages: [commit, push]

exclude: 'docs'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: debug-statements
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: name-tests-test
      args: [--pytest-test-first]
    - id: requirements-txt-fixer
    - id: trailing-whitespace

# Remove unused imports
- repo: https://github.com/PyCQA/autoflake
  rev: v2.1.1
  hooks:
    - id: autoflake

# Sort imports
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files", "--line-length=88"]

# Format the code and notebooks with black
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3.8
    - id: black-jupyter
      language_version: python3.8
